In [3]:
import numpy as np
import matplotlib as pl
import pandas as pd

In [4]:
#1. Create a rank 2 (2D) array that resembles the matrix below.
#[[11 12 13 14]
# [15 16 17 18]]

In [8]:
two_d = np.array([[11 ,12 ,13 ,14], [15 ,16 ,17 ,18]])

In [9]:
print(two_d)

[[11 12 13 14]
 [15 16 17 18]]


# Use the appropriate functions to solve the following questions
1. Create an array with 4 rows and 3 columns of zeros. Your results should look as below:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

In [14]:
col_row = np.zeros((4,3))

In [15]:
print(col_row)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


2.Create an array of ones that has 3 rows and 4 columns. Your results should look as below:
[[1. 1. 1. 1.]
[1. 1. 1. 1.]
[1. 1. 1. 1.]]

In [16]:
three_four = np.ones((3,4))
print(three_four)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


3. Create an array containing integers 4 to 13 inclusive. Your results should look as below:
[4 5 6 7 8 9 10 11 12 13]

In [17]:
uh = np.linspace(4,13,10)
print(uh)

[ 4.  5.  6.  7.  8.  9. 10. 11. 12. 13.]


4. Create an array containing
[0., 1.5, 3., 4.5]

In [18]:
bruh = np.linspace(0,4.5,4)
print(bruh)

[0.  1.5 3.  4.5]


5. Create a 2 by 2 array containing '4' in each position. Your results should look like this:
[[4 4]
 [4 4]]

In [21]:
two = np.array([[4,4],[4,4]])
print(two)

[[4 4]
 [4 4]]


6
. Create 2 matrices:
i. Identity matrix of size 4
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
ii. Diagonal matrix with [10,12] as the diagonals
[[10  0]
 [ 0 12]]

In [23]:
diag = np.zeros((4,4))
diag[0][0] = 1
diag[len(diag)-1][3] = 1

mat = np.matrix(diag)
print(mat)

[[1. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 1.]]


In [25]:
print(np.matrix([[10 , 0],[0,12]]))

[[10  0]
 [ 0 12]]


7. Create a 3 by 3 array with random floats in [0, 10]. Your answer may be different because it is random but it should look something like this:
[[6.3685612  0.61720883 8.93157783]
 [3.69927617 5.79879583 7.62145626]
 [7.21895112 4.02011535 4.48844787]]

In [26]:
three = np.random.rand(3,3)
print(three)

[[0.70959775 0.37280049 0.60488486]
 [0.26243799 0.63263948 0.72933222]
 [0.25829372 0.58979201 0.14821361]]


8. Create a 3 by 3 array with random integers in [10, 20]. Your answer may be different because it is random but it should look something like this:
[[19 11 13]
 [10 11 13]
 [11 14 10]]

In [28]:
ran = np.random.randint(1,420,size=(3,3))
print(ran)

[[ 38  30 362]
 [173 192 160]
 [199 145 395]]


SLICING ARRAYS
1. Use this array for the following practice:
myArray = np.array([[11,12,13], [14,15,16], [17,18,19]])
a. Get a subarray of the first row and first 2 columns. Your results should look like this:
[11 12]
b. Change all elements in 1st and second row to 0. Your results should look like this:
[[ 0  0  0]
 [ 0  0  0]
 [17 18 19]]

In [31]:
myArray = np.array([[11,12,13], [14,15,16], [17,18,19]])
sub = myArray[0][0] , myArray[0][1]
print(sub)
myArray[0,:] = 0
myArray[1,:] = 0

print(myArray)

(11, 12)
[[ 0  0  0]
 [ 0  0  0]
 [17 18 19]]


2. Create an array that contains [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20] and reverse the order.

In [33]:
long = np.array([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
print(long)
long = long[::-1]
print(long)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


RESHAPING
Use this array for the following practice:
myArray = np.array([[11,12,13], [14,15,16]])
Reshape the array to an array with 3 rows. Your results should look like this:
[[11 12]
 [13 14]
 [15 16]]

In [39]:
myArray = np.array([[11,12,13], [14,15,16]])
print(np.reshape(myArray , ((3,2))))

[[11 12]
 [13 14]
 [15 16]]


MATH
Use this array for the following practice:
myArray = np.arange(10)
1. Find the square of every number in array
2. Find the square root of every number in array
3. Multiply the square of each number in array with its respective square root

In [42]:
myArray = np.arange(10)

sq_arr = np.square(myArray)
print(sq_arr)

sqr_arr = np.sqrt(myArray)
print(sqr_arr)

final_arr = np.multiply(sq_arr , sqr_arr)
print(final_arr)

[ 0  1  4  9 16 25 36 49 64 81]
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
[  0.           1.           5.65685425  15.58845727  32.
  55.90169944  88.18163074 129.64181424 181.01933598 243.        ]


ADDING ELEMENTS
Use this array for the following practice:
myArray = np.array([[11,12,13], [14,15,16], [17,18,19]])
1. Add a new row of elements containing 20, 21 and 22
2. Add a new column of elements containing 30, 40 and 50

In [55]:
myArray = np.array([[11,12,13], [14,15,16], [17,18,19]])
new_r= [20,21,22]
new_c=[30,40,50]
myArray=np.vstack((myArray , new_r))
print(myArray)

g = np.concatenate([myArray , new_c])
print(g)

[[11 12 13]
 [14 15 16]
 [17 18 19]
 [20 21 22]]


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

INSERTING ELEMENTS
1. Add 1 column of 1 to this array: myArray = np.zeros((2,2))
2. Add 2 rows of 2 to the answer from part 1
3. Remove the last column
4. Remove the last row

In [63]:
myArray = np.zeros((2,2))
col = [0,0],[0,0]
row = [2,2]
myArray = np.concatenate([myArray , col])
i=0
while i < 2:
    myArray = np.vstack((myArray , row))
    i+=1
myArray = np.delete(myArray , -1 , -1)
myArray = np.delete(myArray , -1 , 0)
print(myArray)

[[0.]
 [0.]
 [0.]
 [0.]
 [2.]]


DELETING ELEMENTS
Remove the elements from the middle column of this array:
myArray = np.matrix([[1, 2, 3], [4, 5, 6], [9, 8, 7]])
Your codes should look like this:
[[1 3]
 [4 6]
 [9 7]]

In [64]:
myArray = np.matrix([[1, 2, 3], [4, 5, 6], [9, 8, 7]])
result_1 = myArray[:, [0, 2]]

# TEST EXERCISE
Replace all odd numbers in the given array with -1
Start with:
exercise_1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Desired output:
[ 0, -1, 2, -1, 4, -1, 6, -1, 8, -1]
Convert a 1-D array into a 2-D array with 3 rows
Start with:
exercise_2 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
Desired output:
[[ 0, 1, 2]
[3, 4, 5]
[6, 7, 8]]
Add 202 to all the values in given array
Start with:
exercise_3 = np.arange(4).reshape(2,-1)
Desired output:
[[202, 203]
[204, 205]]
Generate a 1-D array of 10 random integers. Each integer should be a number between 30 and 40 (inclusive)
Sample of desired output:
[36, 30, 36, 38, 31, 35, 36, 30, 32, 34]
Find the positions of:
elements in x where its value is more than its corresponding element in y, and
elements in x where its value is equals to its corresponding element in y.
Start with these:
x = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89])
y = np.array([21, 7, 3, 45, 10, 29, 55, 4, 37, 18])
Desired output:
(array([1, 2, 4, 5, 6, 7, 8, 9]),) and (array([0]),)
Extract the first four columns of this 2-D array
Start with this:
exercise_6 = np.arange(100).reshape(5,-1)
Desired output:
[[ 0 1 2 3]
[20 21 22 23]
[40 41 42 43]
[60 61 62 63]
[80 81 82 83]]

In [66]:
exercise = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
exercise[exercise % 2 == 1] = -1

In [67]:
exercise_2 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
result_2 = exercise_2.reshape(3, 3)

In [68]:
exercise_3 = np.arange(4).reshape(2, -1) + 202

In [69]:
result_3 = np.random.randint(30, 41, 10)

In [70]:
x = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89])
y = np.array([21, 7, 3, 45, 10, 29, 55, 4, 37, 18])
greater_positions = np.where(x > y)
equal_positions = np.where(x == y)

In [71]:
exercise_6 = np.arange(100).reshape(5, -1)
result_6 = exercise_6[:, 0:4]